// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pczxcuhytzbuzzyrkhdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjenhjdWh5dHpidXp6eXJraGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzQ4NjgsImV4cCI6MjA3MTExMDg2OH0.qIK1jWf21ugzOdEggHekbXjdbQsRYPZMM0vVvNHgWUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});